accounts/urls.py
from django.urls import re_path

from accounts import views as accounts_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    re_path(r'^signup/$', accounts_views.sign_up, name='sign-up'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='log-in'),
    re_path(r'^logout/$', accounts_views.log_out, name='log-out'),
]

django_imdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('imdb_app.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

imdb_app/models.py
from django.contrib.auth.models import User
from django.db import models


GENDER = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other')
)

AWARD_KIND = (
    ('actor', 'Actor'),
    ('movie', 'Movie')
)


class Category(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=4000)
    release_date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE,)
    actors = models.ManyToManyField('Actor', blank=True)
    logo = models.FileField(upload_to='pictures', null=True, blank=True)

    def static_url(self):
        return 'static/' + self.logo.name.split('/')[-1]

    def __str__(self):
        return self.title


class Actor(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateField()
    sex = models.CharField(choices=GENDER, max_length=10)
    nationality = models.CharField(max_length=255)
    alive = models.BooleanField(default=True)

    @property
    def name(self):
        return self.first_name + ' ' + self.last_name

    def __str__(self):
        return self.name


class Award(models.Model):
    name = models.CharField(max_length=255)
    kind = models.CharField(choices=AWARD_KIND, max_length=10)
    movies = models.ManyToManyField(Movie, blank=True)
    actors = models.ManyToManyField(Actor, blank=True)


class Comment(models.Model):
    text = models.TextField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING,)
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING,)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

imdb_app/views/actor_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView

from imdb_app.models import Actor


class ActorListView(LoginRequiredMixin, ListView):
    model = Actor
    context_object_name = 'actors'
    template_name = 'imdb/actors.html'
    paginate_by = 10

    def get_queryset(self):
        actors = Actor.objects.all().order_by('first_name')
        return actors


class ActorDetailView(LoginRequiredMixin, DetailView):
    model = Actor
    context_object_name = 'actor'
    template_name = 'imdb/actor_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ActorDetailView, self).get_context_data(**kwargs)
        context['movies'] = self.get_object().movie_set.all()
        return context


class ActorCreateView(LoginRequiredMixin, CreateView):
    model = Actor
    fields = '__all__'
    template_name = 'imdb/actor_create.html'

    def get_success_url(self):
        return reverse_lazy('actor-detail', kwargs={'pk': self.object.pk})


class ActorEditView(LoginRequiredMixin, UpdateView):
    model = Actor
    fields = '__all__'
    context_object_name = 'actor'
    template_name = 'imdb/actor_edit.html'

    get_success_url = ActorCreateView.get_success_url


class ActorDeleteView(LoginRequiredMixin, DeleteView):
    model = Actor

    def get_success_url(self):
        return reverse('actor')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

imdb_app/views/award_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView

from imdb_app.models import Award


class AwardListView(LoginRequiredMixin, ListView):
    model = Award
    context_object_name = 'awards'
    template_name = 'imdb/awards.html'
    paginate_by = 10

    def get_queryset(self):
        awards = list(Award.objects.all().order_by('name'))
        actor_awards = [a for a in awards if a.kind == 'actor']
        movie_awards = [a for a in awards if a.kind != 'actor']
        awards = []
        while actor_awards or movie_awards:
            if actor_awards:
                awards.append(actor_awards.pop(0))
            if movie_awards:
                awards.append(movie_awards.pop(0))
        return awards


class AwardDetailView(LoginRequiredMixin, DetailView):
    model = Award
    context_object_name = 'award'
    template_name = 'imdb/award_detail.html'


class AwardCreateView(LoginRequiredMixin, CreateView):
    model = Award
    fields = '__all__'
    template_name = 'imdb/award_create.html'

    def form_valid(self, form):
        if form.cleaned_data['kind'] == 'actor':
            form.cleaned_data['movies'] = Award.objects.none()
        else:
            form.cleaned_data['actors'] = Award.objects.none()
        form.save()
        url = reverse_lazy('award-detail', kwargs={'pk': form.instance.pk})
        return HttpResponseRedirect(url)


class AwardEditView(LoginRequiredMixin, UpdateView):
    model = Award
    fields = '__all__'
    context_object_name = 'award'
    template_name = 'imdb/award_edit.html'

    form_valid = AwardCreateView.form_valid


class AwardDeleteView(LoginRequiredMixin, DeleteView):
    model = Award

    def get_success_url(self):
        return reverse('award')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

imdb_app/views/movie_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView

from imdb_app.models import Movie, Comment


class MovieListView(LoginRequiredMixin, ListView):
    model = Movie
    context_object_name = 'movies'
    template_name = 'imdb/movies.html'
    paginate_by = 5

    def get_queryset(self):
        return Movie.objects.all().order_by('title')


class MovieDetailView(LoginRequiredMixin, DetailView):
    model = Movie
    context_object_name = 'movie'
    template_name = 'imdb/movie_detail.html'

    def get_context_data(self, **kwargs):
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(movie_id=self.kwargs['pk'])
        context['comments'] = comments
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            text = request.POST.get('text', '')
            if text.strip():
                Comment.objects.create(text=text, user=request.user,
                                       movie_id=self.kwargs['pk'])
            return HttpResponseRedirect(request.path)

        return super(MovieDetailView, self).dispatch(request, *args, **kwargs)


class MovieCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    fields = '__all__'

    template_name = 'imdb/movie_create.html'

    def get_success_url(self):
        return reverse_lazy('movie-detail', kwargs={'pk': self.object.pk})


class MovieEditView(LoginRequiredMixin, UpdateView):
    model = Movie
    fields = '__all__'
    context_object_name = 'movie'
    template_name = 'imdb/movie_edit.html'

    get_success_url = MovieCreateView.get_success_url


class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie

    def get_success_url(self):
        return reverse('movie')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/imdb/actor_create.html
{% extends 'base.html' %}
{% block title %}Actors - create{% endblock %}
{% block content %}
    <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if field == form.alive %}
                    {% render_field field %}
                {% elif field == form.birth_date %}
                    {% render_field field class="form-control" type="date" %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback" style="display: block">
                        {{ error }}
                    </div>
                {% endfor %}

                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/imdb/actor_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Actors - {{ actor.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="list-group list-group-flush">
                <li class="list-group-item" style="border: none;">
                    <strong>Name</strong> : {{ actor.name }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Sex</strong>: {{ actor.sex.title }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Date of birth</strong>: {{ actor.birth_date | date:"SHORT_DATE_FORMAT" }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Nation</strong>: {{ actor.nationality }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Filmography: </strong>:
                    <ul class="list-group list-group-flush">
                        {% for movie in movies %}
                            <li class="list-group-item" style="border: none">
                                <a href="{% url 'movie-detail' movie.pk %}">{{ movie.title }}</a>
                            </li>
                        {% empty %}
                            <li class="list-group-item" style="border: none"> N/A </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="list-group-item" style="border: none">
                    <br />
                    <a href="{% url 'actor' %}">See other Actors</a>
                </li>
            </ul>
        </div>
    </div>

{% endblock %}

templates/imdb/actor_edit.html
{% extends 'imdb/actor_create.html' %}
{% block title %}Actors - {{ actor.name }}{% endblock %}

templates/imdb/actors.html
{% extends 'base.html' %}
{% block title %}Actors{% endblock %}

{% block content %}
    <h2>Actors <a class="float-right mr-3 btn btn-primary" href="{% url 'actor-create' %}">New actor</a></h2>
    <hr/>
    <div>
        <ul class="list-group list-group-flush">
            {% for actor in actors %}
                <li class="list-group-item media">
                    <span style="height: 50px">
                        <a href="{% url 'actor' %}{{ actor.pk }}">
                        {{ actor.name }}
                        </a>
                    </span>
                    <span id="toHideDiv" style="display: none">
                        <a href="{% url 'actor-delete' actor.pk %}" class="float-right mr-3 btn btn-secondary">
                        Delete
                    </a>
                    <a href="{% url 'actor-edit' actor.pk %}" class="float-right mr-3 btn btn-primary">
                        Edit
                    </a>
                    </span>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% include 'includes/paginator.html' %}
{% endblock %}

templates/imdb/award_create.html
{% extends 'base.html' %}
{% block title %}Awards - create{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% load widget_tweaks %}


        <div class="form-group">
            {{ form.name.label_tag }}
            {% render_field form.name class="form-control" %}
            {% for error in form.name.errors %}
                <div class="invalid-feedback" style="display: block">
                    {{ error }}
                </div>
            {% endfor %}
            {% if form.name.help_text %}
                <small class="form-text text-muted">
                    {{ form.name.help_text }}
                </small>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.kind.label_tag }}
            {% render_field form.kind class="form-control" %}
            {% for error in form.kind.errors %}
                <div class="invalid-feedback" style="display: block">
                    {{ error }}
                </div>
            {% endfor %}
            {% if form.kind.help_text %}
                <small class="form-text text-muted">
                    {{ form.kind.help_text }}
                </small>
            {% endif %}
        </div>

        <div class="form-group" id="grpMovies">
            {{ form.movies.label_tag }}
            {% render_field form.movies class="form-control" %}
            {% for error in form.movies.errors %}
                <div class="invalid-feedback" style="display: block">
                    {{ error }}
                </div>
            {% endfor %}
            {% if form.movies.help_text %}
                <small class="form-text text-muted">
                    {{ form.movies.help_text }}
                </small>
            {% endif %}
        </div>

        <div class="form-group" id="grpActors">
            {{ form.actors.label_tag }}
            {% render_field form.actors class="form-control" %}
            {% for error in form.actors.errors %}
                <div class="invalid-feedback" style="display: block">
                    {{ error }}
                </div>
            {% endfor %}
            {% if form.actors.help_text %}
                <small class="form-text text-muted">
                    {{ form.actors.help_text }}
                </small>
            {% endif %}
        </div>


        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

{% block scripts %}
        <script>
            function showGroup() {
                let kind = $('#id_kind').val();
                if (kind === 'actor') {
                    $('#grpActors').show();
                    $('#grpMovies').hide();
                } else if (kind === 'movie') {
                    $('#grpActors').hide();
                    $('#grpMovies').show();
                } else {
                    $('#grpActors').hide();
                    $('#grpMovies').hide();
                }
            }

            $( document ).ready(function() {
                showGroup();
                $('#id_kind').on('change', showGroup);
            });
        </script>
{% endblock %}

templates/imdb/award_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Awards - {{ award.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="list-group list-group-flush">
                <li class="list-group-item" style="border: none;">
                    <strong>Name</strong> : {{ award.name }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Kind</strong>: {{ award.kind.title }}
                </li>
                <li class="list-group-item" style="border: none">
                    {% if award.kind == "movie" %}
                        <strong>Movies win this</strong>:
                        <ul>
                            {% for movie in award.movies.iterator %}
                                <li> <a href="{% url 'movie-detail' movie.pk %}">{{ movie.title }}</a> </li>
                            {% empty %}
                                <li>N/A</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <strong>Actors win this</strong>:
                        <ul>
                            {% for actor in award.actors.iterator %}
                                <li><a href="{% url 'actor-detail' actor.pk %}">{{ actor.name }}</a></li>
                            {% empty %}
                                N/A
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
                <li class="list-group-item" style="border: none">
                    <br />
                    <a href="{% url 'award' %}">See other Awards</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/imdb/award_edit.html
{% extends 'imdb/award_create.html' %}
{% block title %}Awards - {{ award.name }}{% endblock %}

templates/imdb/awards.html
{% extends 'base.html' %}
{% block title %}Awards{% endblock %}

{% block content %}
    <h2>Awards <a class="float-right mr-3 btn btn-primary" href="{% url 'award-create' %}">New award</a></h2>
    <hr/>
    <div>
        <h3>Movies</h3>
        <ul class="list-group list-group-flush">
            {% for award in awards %}
                {% if award.kind == "movie" %}
                    <li class="list-group-item">
                        <a href="{% url 'award' %}{{ award.pk }}">
                            {{ award.name }}
                        </a>
                        <a href="{% url 'award-delete' award.pk %}" class="float-right mr-3 btn btn-secondary">
                            Delete
                        </a>
                        <a href="{% url 'award-edit' award.pk %}" class="float-right mr-3 btn btn-primary">
                            Edit
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <h3> Actors </h3>
        <ul class="list-group list-group-flush">
            {% for award in awards %}
                {% if award.kind == "actor" %}
                    <li class="list-group-item">
                        <a href="{% url 'award' %}{{ award.pk }}">
                            {{ award.name }}
                        </a>
                        <a href="{% url 'award-delete' award.pk %}" class="float-right mr-3 btn btn-secondary">
                            Delete
                        </a>
                        <a href="{% url 'award-edit' award.pk %}" class="float-right mr-3 btn btn-primary">
                            Edit
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    {% include 'includes/paginator.html' %}
{% endblock %}

templates/imdb/comment_edit.html
{% extends 'base.html' %}
{% block content %}
    <h5> Edit comment: </h5>
    <form method="post" novalidate style="width: 100%">
        {% load widget_tweaks %}
        {% csrf_token %}
        {% render_field form.text class="form-control" style="width: 100%" %}
        {% for error in form.text.errors %}
            <div class="invalid-feedback" style="display: block">
                Please fill out the comment.
            </div>
        {% endfor %}
        <br/>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/imdb/home.html
{% extends 'base.html' %}

{% block title %}Home page{% endblock %}
{% block content %}
<img width="100%" src="https://i.pinimg.com/originals/23/02/b7/2302b739fe2bff298986a1801e156a0a.gif">
{% endblock %}

templates/imdb/movie_create.html
{% extends 'base.html' %}
{% block title %}Movies - create{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% load widget_tweaks %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% if field == form.release_date %}
                    {% render_field field type="date" class="form-control" %}
                {% elif field == form.logo %}
                    <div style="margin-left: 4em;">
                        {% render_field field %}
                    </div>
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback" style="display: block">
                        {{ error }}
                    </div>
                {% endfor %}
                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

templates/imdb/movie_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Movies - {{ movie.title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4 text-center">
            {% if movie.logo %}
                <img width="100%" style="max-height: 25em" src="{{ movie.logo.url }}" class="rounded" alt="...">
            {% else %}
                <img width="100%" style="max-height: 25em" src="{% static 'nopicture.gif' %}" class="rounded" alt="...">
            {% endif %}
        </div>

        <div class="col-8">
            <ul class="list-group list-group-flush">
                <li class="list-group-item" style="border: none;">
                    <strong>Title</strong> : {{ movie.title }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Description</strong>: {{ movie.description }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Release date</strong>: {{ movie.release_date }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Category</strong>: {{ movie.category }}
                </li>
                <li class="list-group-item" style="border: none">
                    <strong>Actors</strong>:
                    <ul class="list-group list-group-flush">
                        {% for actor in movie.actors.iterator %}
                            <li class="list-group-item" style="border: none">
                                <a href="{% url 'actor-detail' actor.pk %}">{{ actor.name }}</a>
                            </li>
                        {% empty %}
                            <li class="list-group-item">
                                N/A
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="list-group-item text-right" style="border: none">
                    <a href="{% url 'movie' %}">See other Movies</a>
                </li>
            </ul>
        </div>
    </div>
    <br/> <br/>

    <div class="card">
        <div class="card-header">
            Comments
        </div>
        <div class="card-body">
            <div id="commemt_section">
                {% for comment in comments %}
                    <div class="card" style="margin-bottom: 10px;">
                        <div class="card-header">
                            <strong>{{ comment.user }}</strong>
                            <small class="float-right"> Last modified: {{ comment.modified | naturaltime }}</small>
                        </div>
                        <div class="card-body">
                            <div id="comment_{{ forloop.counter }}">
                                <p>{{ comment.text }}</p>
                                {% if request.user == comment.user %}
                                    <a href="{% url 'comment-delete' comment.pk %}" class="btn btn-default float-right">Delete</a>
                                    <a href="{% url 'comment-edit' comment.pk %}" class="btn btn-default float-right">Edit</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <br/>
            <h5 class="card-title">Leave your reply</h5>
            <form id="comment_form" method="post" style="width: 100%">
                {% load widget_tweaks %}
                {% csrf_token %}
                <textarea class="form-control" placeholder="Message" name="text" id="comment" cols="100" rows="10" required></textarea>
                <br/>
                <button type="submit" class="float-right btn btn-primary">Send</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/imdb/movie_edit.html
{% extends 'imdb/movie_create.html' %}

{% block title %}Movies - {{ movie.title }}{% endblock %}

templates/imdb/movies.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Movies{% endblock %}

{% block content %}
    <h2>Movies <a class="float-right mr-3 btn btn-primary" href="{% url 'movie-create' %}">New movie</a></h2>
    <hr/>
    <div>
        <ul class="list-group list-group-flush">
            {% for movie in movies %}
                <li class="list-group-item">
                    <div class="media position-relative">
                        {% if movie.logo %}
                            <img class="img-rounded mr-3" width="100px" height="100px" src="{{ movie.logo.url }}" alt="{{ movie.title }}">
                        {% else %}
                            <img class="img-rounded mr-3" width="100px" height="100px" src="{% static 'nopicture.gif' %}" alt="{{ movie.title }}">
                        {% endif %}
                        <div class="media-body">
                            <a href="{% url 'movie' %}{{ movie.pk }}">
                                <h5 class="mt-0"><span class="movie-title">{{ movie.title }}</span></h5>
                            </a>
                            <span>{{ movie.description | truncatechars:130 }}</span>
                            <span id="toHideDiv" style="display: none;">
                                    <a href="{% url 'movie-delete' movie.pk %}" class="btn btn-secondary ml-3 float-right">Delete</a>
                                    <a href="{% url 'movie-edit' movie.pk %}" class="btn btn-primary float-right">Edit</a>
                            </span>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% include 'includes/paginator.html' %}
{% endblock %}